
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
/home/mjharvey/miniconda3/bin/psi4: line 8: 34647 Aborted                 "$D/bin/psi4.bin" "$@"
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

Optimizer: Optimization complete!
An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

Optimizer: Optimization complete!
An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
New linear angles
Optimizer: Optimization complete!
Optimizer: Optimization complete!
/home/mjharvey/miniconda3/bin/psi4: line 8: 40760 Aborted                 "$D/bin/psi4.bin" "$@"
Optimizer: Optimization complete!
/home/mjharvey/miniconda3/bin/psi4: line 8: 40944 Aborted                 "$D/bin/psi4.bin" "$@"
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

TypeError: 'NoneType' object is not iterable
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
Optimizer: Optimization complete!
An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 46, in <module>

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 1026, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/driver.py", line 592, in gradient
    wfn = procedures['gradient'][lowername](lowername, molecule=molecule, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1705, in run_scf_gradient
    ref_wfn = run_scf(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1689, in run_scf
    scf_wfn = scf_helper(name, **kwargs)

  File "/export131/home/mjharvey/miniconda3/share/psi4/python/procedures/proc.py", line 1170, in scf_helper
    scf_wfn = psi4.scf(ref_wfn, precallback, postcallback)

RuntimeError: 
Fatal Error: Iterations did not converge.
Error occurred in file: /scratch/cdsgroup/conda-builds/work/src/lib/libparallel/process.cc on line: 207
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::die_if_not_converged()
psi::scf::HF::finalize_E()
psi::scf::HF::compute_energy()
psi::scf::scf(boost::shared_ptr<psi::Wavefunction>, psi::Options&, _object*, _object*)

/home/mjharvey/miniconda3/bin/psi4: line 8: 45118 Aborted                 "$D/bin/psi4.bin" "$@"
/home/mjharvey/miniconda3/bin/psi4: line 8: 45127 Aborted                 "$D/bin/psi4.bin" "$@"
/home/mjharvey/miniconda3/bin/psi4: line 8: 45136 Aborted                 "$D/bin/psi4.bin" "$@"
/home/mjharvey/miniconda3/bin/psi4: line 8: 45145 Aborted                 "$D/bin/psi4.bin" "$@"
/home/mjharvey/miniconda3/bin/psi4: line 8: 45154 Aborted                 "$D/bin/psi4.bin" "$@"
Please cite -- HTMD: High-Throughput Molecular Dynamics for Molecular Discovery
J. Chem. Theory Comput., 2016, 12 (4), pp 1845-1852. 
http://pubs.acs.org/doi/abs/10.1021/acs.jctc.6b00049


You are on the latest HTMD version (unpackaged : /home/mjharvey/working/acellera/htmd/htmd).
 === Parameterizing input.mol2 ===

Dihedral 0: 9-6-5-8
 Has equivalent dihedrals through symmetry: 
 Dihedral 8-5-6-10
 Dihedral 8-5-6-11
Dihedral 1: 8-5-2-1
Dihedral 2: 5-2-1-3
 Has equivalent dihedrals through symmetry: 
 Dihedral 5-2-1-4
Net Charge: 0
Equivalent atom groups:
 H1
 C1
 O1
 F1 F2
 C2
 C3
 CL1
 H2
 F3 F4 F5
Soft dihedrals:
 F3 C3 C2 H2
 H2 C2 O1 C1
 C2 O1 C1 F1

 == Minimizing ==



 == Charge fitting ==


Charge Chi^2 score : 0.012817 : GOOD
QM Dipole   : -1.553300 -0.451600 0.226400 ; 1.633300
MM Dipole   : -1.554062 -0.493286 0.022690 ; 1.630630
Dipole Chi^2 score : 0.000007 : GOOD


 == Fitting torsion F3-C3-C2-H2 ==

Duplicating types..
Creating new type f_0 from f for atom F3
Creating new type c3_0 from c3 for atom C3
Creating new type c3_1 from c3 for atom C2
Creating new type h2_0 from h2 for atom H2
 Dih F3-C3-C2-H2 and F3-C3-C2-H2 are equivalent 
 Dih F3-C3-C2-H2 and H2-C2-C3-F4 are equivalent 
 Dih F3-C3-C2-H2 and H2-C2-C3-F5 are equivalent 


Torsion F3-C3-C2-H2 Chi^2 score : 0.519024 : GOOD

 == Fitting torsion H2-C2-O1-C1 ==

Duplicating types..
Creating new type os_0 from os for atom O1
Creating new type c3_2 from c3 for atom C1
 Dih H2-C2-O1-C1 and H2-C2-O1-C1 are equivalent 


Torsion H2-C2-O1-C1 Chi^2 score : 19.610928 : CHECK

 == Fitting torsion C2-O1-C1-F1 ==

Duplicating types..
Creating new type f_1 from f for atom F1
 Dih C2-O1-C1-F1 and C2-O1-C1-F1 are equivalent 
 Dih C2-O1-C1-F1 and C2-O1-C1-F2 are equivalent 


Torsion C2-O1-C1-F1 Chi^2 score : 2.753929 : GOOD
 == Diagnostic Energies == 

 Bond     : 5.443310
 Angle    : 1.680888
 Dihedral : -3.248443
 Improper : 0.000000
 Electro  : 6.853008
 VdW      : 2.665540


 == Output to parameters/GAFF2/cc-pVTZ ==

